Fixed .gz processing; added command line arguments
- Fixed .gz processing
- Added command line arguments -e and -r
- Various improvements

diff --git a/rom-sha1sum b/rom-sha1sum
--- a/rom-sha1sum
+++ b/rom-sha1sum
@@ -13,11 +13,44 @@
 # Project homepage: https://github.com/hippie68/rom-sha1sum
 
 MAX_DECOMPRESSION_RECURSION_LVL=1 # Increase to parse deeply nested archives.
-FILE_EXTENSIONS=(3ds gb gba gbc gcm gcz gen gg md n64 ngc ngp nds nes nez nsp pce sfc smc smd srl v64 vb vpk ws wsc xci xiso z64 zip gz 7z) # Note: additional archives must be handled in process_file().
-IFS=\| FILE_EXT_REGEX="\\.(${FILE_EXTENSIONS[*]})\$"
+FILE_EXTENSIONS=(3ds gb gba gbc gcm gcz gen gg md n64 ngc ngp nds nes nez nsp pce sfc smc smd srl v64 vb vpk wbfs ws wsc xci xiso z64 zip gz 7z) # Note: additional archives must be handled in process_file().
+declare FILE_EXT_REGEX
+
+# $1: name of an array containing file extensions (without dots)
+create_file_ext_regex() {
+    local -n extensions=$1
+    IFS=\| FILE_EXT_REGEX="\\.(${extensions[*]})\$"
+}
 
 print_usage() {
-    echo "Usage: $(basename "$0") FILE/DIRECTORY [...]"
+    cat <<EOF
+Usage: $(basename "$0") FILE/DIRECTORY [...]
+
+Options:
+  -e LIST  Only process files that have one the file extensions specified
+           without dots in comma-separated argument LIST.
+  -r       Parse directories recursively.
+EOF
+}
+
+# $1: string, $2: delimiter character, $3: the output array's name
+split_string() {
+    local -n array=$3
+    readarray -t -d "$2" array <<< "$1"
+    array[-1]=${array[-1]::-1}
+}
+
+parse_args() {
+    while getopts e:r opt; do
+        case $opt in
+            r) opt_recursive=1;;
+            e)
+                split_string "$OPTARG" , opt_extensions
+                create_file_ext_regex opt_extensions
+                ;;
+            *) print_usage; exit 1;;
+        esac
+    done
 }
 
 get_magic() {
@@ -60,6 +93,10 @@ sha1sum_skip_n() {
     fi
 }
 
+warning() {
+    echo -e "\033[1;33mWARNING: \033[0m$1" >&2
+}
+
 error() {
     echo -e "\033[1;31mERROR: \033[0m$1" >&2
 }
@@ -74,8 +111,16 @@ max_recursion_reached() {
 }
 
 create_archive_wildcards() {
+    local -a extensions
+    if [[ -v opt_extensions ]]; then
+        extensions=$opt_extensions
+    else
+        extensions=("${FILE_EXTENSIONS[@]}")
+    fi
+
     declare -ag ARCHIVE_FILE_WILDCARDS
-    ARCHIVE_FILE_WILDCARDS=("${FILE_EXTENSIONS[@]}")
+    # ARCHIVE_FILE_WILDCARDS=("${FILE_EXTENSIONS[@]}")
+    ARCHIVE_FILE_WILDCARDS=("${extensions[@]}")
     for ((i = 0; i < ${#ARCHIVE_FILE_WILDCARDS[@]}; i++)) {
         ARCHIVE_FILE_WILDCARDS[i]="*?.${ARCHIVE_FILE_WILDCARDS[$i]}"
     }
@@ -94,56 +139,88 @@ update_archive_chain() {
 # $1: filename, $2: recursion level, $3: archive chain
 process_file() {
     local archive_chain=$3
-    case $(get_magic "$1") in
+    local magic
+    if ! magic=$(get_magic "$1"); then
+        error "Could not read magic number from file \"$1\""
+        exit 1
+    fi
+
+    # Process archive file
+    if [[ $1 =~ .*\.(zip|gz|7z) ]]; then
+        max_recursion_reached "$1" "$2" && return
+
+        case $1 in
+            *.zip)
+                if [[ $magic != $'PK\x03\x04' ]]; then
+                    warning "Not a ZIP file: \"$1\""
+                    return
+                fi
+
+                [[ ! -v ARCHIVE_FILE_WILDCARDS ]] && create_archive_wildcards
+                local tmp_dir
+                tmp_dir=$(mktemp --directory) || exit 1
+                unzip -d "$tmp_dir" "$1" "${ARCHIVE_FILE_WILDCARDS[@]}" &> /dev/null
+                local ret=$?
+                if [[ $ret -eq 0 || $ret -eq 11 ]]; then
+                    update_archive_chain archive_chain "$1"
+                    readarray -d '' < <(find "$tmp_dir" -type f -print0 2> /dev/null)
+                    for file in "${MAPFILE[@]}"; do
+                        process_file "$file" $(($2 + 1)) "$archive_chain"
+                    done
+                else
+                    error "Could not extract ZIP file \"$1\""
+                fi
+                rm -r "$tmp_dir" || exit 1
+                ;;
+            *.gz)
+                if [[ $1 == *.tar.gz ]]; then
+                    warning "Ignoring file \"$1\" (.tar.gz not supported)"
+                    return
+                fi
+                if [[ $magic != $'\x1f\x8b'* ]]; then
+                    warning "Not a gzip file: \"$1\""
+                    return
+                fi
+
+                local tmp_dir
+                tmp_dir=$(mktemp --directory) || exit 1
+                tmp_file="$tmp_dir/$(basename "${1%.gz}")"
+                if gunzip --to-stdout "$1" > "$tmp_file"; then
+                    update_archive_chain archive_chain "$1"
+                    process_file "$tmp_file" $(($2 + 1)) "$archive_chain"
+                else
+                    error "Could not extract gzip file \"$1\""
+                fi
+                rm -r "$tmp_dir" || exit 1
+                ;;
+            *.7z)
+                if [[ $magic != $'7z\xbc\xaf' ]]; then
+                    warning "Not a 7-Zip file: \"$1\""
+                    return
+                fi
+
+                [[ ! -v ARCHIVE_FILE_WILDCARDS ]] && create_archive_wildcards
+                local tmp_dir
+                tmp_dir=$(mktemp --directory) || exit 1
+                if 7za x -o"$tmp_dir" "$1" "${ARCHIVE_FILE_WILDCARDS[@]}" > /dev/null; then
+                    update_archive_chain archive_chain "$1"
+                    readarray -d '' < <(find "$tmp_dir" -type f -print0 2> /dev/null)
+                    for file in "${MAPFILE[@]}"; do
+                        process_file "$file" $(($2 + 1)) "$archive_chain"
+                    done
+                else
+                    error "Could not extract 7-Zip file \"$1\""
+                fi
+                rm -r "$tmp_dir" || exit 1
+                ;;
+        esac
+        return
+    fi
+
+    # Process non-archive file
+    case $magic in
         $'NES\x1a')
             sha1sum_skip_n "$1" 16 "$archive_chain"
-            ;;
-        $'PK\x03\x04') # ZIP
-            max_recursion_reached "$1" "$2" && return
-            [[ ! -v ARCHIVE_FILE_WILDCARDS ]] && create_archive_wildcards
-            local tmp_dir
-            tmp_dir=$(mktemp --directory) || exit 1
-            unzip -d "$tmp_dir" "$1" "${ARCHIVE_FILE_WILDCARDS[@]}" &> /dev/null
-            local ret=$?
-            if [[ $ret -eq 0 || $ret -eq 11 ]]; then
-                update_archive_chain archive_chain "$1"
-                readarray -d '' < <(find "$tmp_dir" -type f -print0)
-                for file in "${MAPFILE[@]}"; do
-                    process_file "$file" $(($2 + 1)) "$archive_chain"
-                done
-            else
-                error "Could not extract ZIP file \"$1\""
-            fi
-            rm -r "$tmp_dir" || exit 1
-            ;;
-        $'\x1f\x8b'*) # gzip
-            max_recursion_reached "$1" "$2" && return
-            local tmp_dir
-            tmp_dir=$(mktemp --directory) || exit 1
-            tmp_file="$tmp_dir/${1%.gz}"
-            if gunzip --to-stdout "$1" > "$tmp_file"; then
-                update_archive_chain archive_chain "$1"
-                process_file "$tmp_file" $(($2 + 1)) "$archive_chain"
-            else
-                error "Could not extract gzip file \"$1\""
-            fi
-            rm -r "$tmp_dir" || exit 1
-            ;;
-        $'7z\xbc\xaf')
-            max_recursion_reached "$1" "$2" && return
-            [[ ! -v ARCHIVE_FILE_WILDCARDS ]] && create_archive_wildcards
-            local tmp_dir
-            tmp_dir=$(mktemp --directory) || exit 1
-            if 7za x -o"$tmp_dir" "$1" "${ARCHIVE_FILE_WILDCARDS[@]}" > /dev/null; then
-                update_archive_chain archive_chain "$1"
-                readarray -d '' < <(find "$tmp_dir" -type f -print0)
-                for file in "${MAPFILE[@]}"; do
-                    process_file "$file" $(($2 + 1)) "$archive_chain"
-                done
-            else
-                error "Could not extract 7-Zip file \"$1\""
-            fi
-            rm -r "$tmp_dir" || exit 1
             ;;
         *)
             shopt -s nocasematch
@@ -158,14 +235,11 @@ process_file() {
     esac
 }
 
-if [[ ! $1 ]]; then
-    print_usage
-    exit 0
-fi
-
 parse_file() {
     if [[ -d $1 ]]; then
-        readarray -d '' files < <(find "$1" -type f -regextype posix-extended -regex ".*$FILE_EXT_REGEX" -print0)
+        local maxdepth
+        [[ -v opt_recursive ]] || maxdepth=(-maxdepth 1)
+        readarray -d '' files < <(find "$1" "${maxdepth[@]}" -type f -regextype posix-extended -regex ".*$FILE_EXT_REGEX" -print0 2> /dev/null)
         for f in "${files[@]}"; do
             parse_file "$f"
         done
@@ -175,6 +249,16 @@ parse_file() {
         process_file "$1" 0
     fi
 }
+
+# ------------------------------------------------------------------------------
+
+parse_args "$@"
+shift $((OPTIND - 1))
+if [[ ! $1 ]]; then
+    print_usage
+    exit 0
+fi
+[[ ! -v FILE_EXT_REGEX ]] && create_file_ext_regex FILE_EXTENSIONS
 
 for file in "$@"; do
     parse_file "$file"
