Archive support is now fully optional
- Archive support is now fully optional
- The help screen lists the status of optional external programs

diff --git a/rom-checksum b/rom-checksum
--- a/rom-checksum
+++ b/rom-checksum
@@ -26,9 +26,32 @@ create_file_ext_regex() {
     IFS=\| FILE_EXT_REGEX="\\.(${extensions[*]})\$"
 }
 
+external_programs_status() {
+    local error='\033[1;33mNOT FOUND\033[0m'
+    local path_crc32 path_unzip path_gunzip path_7za
+    [[ -v opt_crc32_enabled ]] && path_crc32=$(hash -t crc32)
+    [[ -v opt_unzip_enabled ]] && path_unzip=$(hash -t unzip)
+    [[ -v opt_gunzip_enabled ]] && path_gunzip=$(hash -t gunzip)
+    [[ -v opt_7za_enabled ]] && path_7za=$(hash -t 7za)
+
+    while read -r line; do echo -e "$line"; done << EOF
+crc32  -> ${path_crc32-$error}
+unzip  -> ${path_unzip-$error}
+gunzip -> ${path_gunzip-$error}
+7za    -> ${path_7za-$error}
+EOF
+}
+
 print_usage() {
     cat <<EOF
-Usage: $(basename "$0") FILE/DIRECTORY [...]
+Usage: $(basename "$0") FILE|DIRECTORY [...]
+
+This script calculates both file checksums and (if supported) ROM checksums for
+ROM files and ROM files inside archives.
+It requires GNU coreutils and at least Bash 4.4.
+
+Status of optional external programs:
+$(external_programs_status)
 
 Options:
   -e LIST  Only process files whose file extensions are specified in comma-
@@ -110,13 +133,14 @@ print_checksum() {
     printf '%s: %s\n' "$1" "${2^^}"
 }
 
-# Do sha1sum for file $1, but skip $2 bytes. $3: archive name
+# $1: filename, $2: ROM offset, $3: archive name
 print_checksums() {
     [[ -v printed_once ]] && echo
-
     print_filename "$1" "$3"
     local crc32 md5 sha1
-    if [[ ! -v opt_crc32_disabled ]]; then
+
+    # File checksums
+    if [[ -v opt_crc32_enabled ]]; then
         crc32_to_var "$1" 0 crc32
         print_checksum "File CRC32" "$crc32"
     fi
@@ -125,8 +149,9 @@ print_checksums() {
     sha1sum_to_var "$1" 0  sha1
     print_checksum "File SHA-1" "$sha1"
 
+    # ROM checksums
     if [[ $2 -gt 0 ]]; then
-        if [[ ! -v opt_crc32_disabled ]]; then
+        if [[ -v opt_crc32_enabled ]]; then
             crc32_to_var "$1" "$2" crc32
             print_checksum "ROM CRC32" "$crc32"
         fi
@@ -150,7 +175,7 @@ error() {
 # $1: filename, $2: recursion level
 max_recursion_reached() {
     if [[ $2 -gt $MAX_DECOMPRESSION_RECURSION_LVL ]]; then
-        error "Ignoring nested archive file (too many recursions): \"$1\""
+        warning "Ignoring nested archive file (too many recursions): \"$1\""
         return 0
     fi
     return 1
@@ -165,7 +190,6 @@ create_archive_wildcards() {
     fi
 
     declare -ag ARCHIVE_FILE_WILDCARDS
-    # ARCHIVE_FILE_WILDCARDS=("${FILE_EXTENSIONS[@]}")
     ARCHIVE_FILE_WILDCARDS=("${extensions[@]}")
     for ((i = 0; i < ${#ARCHIVE_FILE_WILDCARDS[@]}; i++)) {
         ARCHIVE_FILE_WILDCARDS[i]="*?.${ARCHIVE_FILE_WILDCARDS[$i]}"
@@ -197,6 +221,7 @@ process_file() {
 
         case $1 in
             *.zip)
+                [[ -v opt_unzip_enabled ]] || return
                 if [[ $magic != $'PK\x03\x04' ]]; then
                     warning "Not a ZIP file: \"$1\""
                     return
@@ -219,6 +244,7 @@ process_file() {
                 rm -r "$tmp_dir" || exit 1
                 ;;
             *.gz)
+                [[ -v opt_gunzip_enabled ]] || return
                 if [[ $1 == *.tar.gz ]]; then
                     warning "Ignoring file \"$1\" (.tar.gz not supported)"
                     return
@@ -240,6 +266,7 @@ process_file() {
                 rm -r "$tmp_dir" || exit 1
                 ;;
             *.7z)
+                [[ -v opt_7za_enabled ]] || return
                 if [[ $magic != $'7z\xbc\xaf' ]]; then
                     warning "Not a 7-Zip file: \"$1\""
                     return
@@ -298,9 +325,10 @@ parse_file() {
 
 # ------------------------------------------------------------------------------
 
-if ! hash crc32; then
-    opt_crc32_disabled=1
-fi
+hash crc32 && opt_crc32_enabled=1
+hash unzip && opt_unzip_enabled=1
+hash gunzip && opt_gunzip_enabled=1
+hash 7za && opt_7za_enabled=1
 
 parse_args "$@"
 shift $((OPTIND - 1))
